### ISSUE TITLE
Former Committee link needs repositioning on page

### ISSUE THREAD

**Issue by Twigonometry** [ShefESH/SeshWebsite#79]
Link to `/committee_old.html` floats in middle of  `/committee` page

**Comment by Twigonometry** [comment]
@sasouthwell1 is going to move this under the "Meet the Committee!" banner. Also discussed with @vladcranga adding a button on other page to go back to current committee, and adding a dropdown in the navbar for Current/Previous, so decide between you who is taking what from those features

**Comment by vladcranga** [comment]
- [X ] Center the text on the /committee page
- [X ] Center the text on the /committee_old page
- [X ] Link back to the current committee page on the former committee page

**Comment by Twigonometry** [comment]
This is finished as of [2b726a0d](https://github.com/ShefESH/SeshWebsite/commit/2b726a0d1bd15c56c4f97b4d53f2e95dea4ed04f)
